"""rename address

Revision ID: 26247885dc48
Revises: 2ffda07d5350
Create Date: 2024-06-03 22:40:12.475728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26247885dc48'
down_revision = '2ffda07d5350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
